# docker-compose.yml in root folder
version: "3.9"
services:
  app:
    container_name: SpringBootApp
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "9086:9086"
    volumes:
      - ./:/app/app