spring:
  cloud:
    gateway:
      routes:
        - id: ApplicationMS_kbe
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/laptops/**
        - id: CalculatorMS_kbe
          uri: http://localhost:8085/
          predicates:
            - Path=/api/v1/calculator/**