
spring:
  cloud:
    gateway:
      routes:
        - id: ApplicationMS_kbe
          uri: http://localhost:8082/
          predicates:
            - Path=/api/laptops/**
        - id: CalculatorMS_kbe
          uri: http://localhost:8081/
          predicates:
            - Path=/api/calculator/**